// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/author_service/author.proto

package author_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Author struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{0}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Author) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Author) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Author) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Author) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateAuthorRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthorRequest) Reset()         { *m = CreateAuthorRequest{} }
func (m *CreateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorRequest) ProtoMessage()    {}
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{1}
}

func (m *CreateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorRequest.Unmarshal(m, b)
}
func (m *CreateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorRequest.Merge(m, src)
}
func (m *CreateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorRequest.Size(m)
}
func (m *CreateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorRequest proto.InternalMessageInfo

func (m *CreateAuthorRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type CreateAuthorResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthorResponse) Reset()         { *m = CreateAuthorResponse{} }
func (m *CreateAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorResponse) ProtoMessage()    {}
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{2}
}

func (m *CreateAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorResponse.Unmarshal(m, b)
}
func (m *CreateAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorResponse.Marshal(b, m, deterministic)
}
func (m *CreateAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorResponse.Merge(m, src)
}
func (m *CreateAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorResponse.Size(m)
}
func (m *CreateAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorResponse proto.InternalMessageInfo

func (m *CreateAuthorResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAuthorRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorRequest) Reset()         { *m = GetAuthorRequest{} }
func (m *GetAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorRequest) ProtoMessage()    {}
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{3}
}

func (m *GetAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorRequest.Unmarshal(m, b)
}
func (m *GetAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorRequest.Merge(m, src)
}
func (m *GetAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorRequest.Size(m)
}
func (m *GetAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorRequest proto.InternalMessageInfo

func (m *GetAuthorRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAuthorRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAuthorRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetAuthorResponse struct {
	Authors              []*Author `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAuthorResponse) Reset()         { *m = GetAuthorResponse{} }
func (m *GetAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorResponse) ProtoMessage()    {}
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{4}
}

func (m *GetAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorResponse.Unmarshal(m, b)
}
func (m *GetAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorResponse.Merge(m, src)
}
func (m *GetAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorResponse.Size(m)
}
func (m *GetAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorResponse proto.InternalMessageInfo

func (m *GetAuthorResponse) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

type GetAuthorByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorByIdRequest) Reset()         { *m = GetAuthorByIdRequest{} }
func (m *GetAuthorByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorByIdRequest) ProtoMessage()    {}
func (*GetAuthorByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{5}
}

func (m *GetAuthorByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorByIdRequest.Unmarshal(m, b)
}
func (m *GetAuthorByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorByIdRequest.Merge(m, src)
}
func (m *GetAuthorByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorByIdRequest.Size(m)
}
func (m *GetAuthorByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorByIdRequest proto.InternalMessageInfo

func (m *GetAuthorByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateAuthorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAuthorRequest) Reset()         { *m = UpdateAuthorRequest{} }
func (m *UpdateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthorRequest) ProtoMessage()    {}
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{6}
}

func (m *UpdateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthorRequest.Unmarshal(m, b)
}
func (m *UpdateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthorRequest.Merge(m, src)
}
func (m *UpdateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthorRequest.Size(m)
}
func (m *UpdateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthorRequest proto.InternalMessageInfo

func (m *UpdateAuthorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAuthorRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type UpdateAuthorResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAuthorResponse) Reset()         { *m = UpdateAuthorResponse{} }
func (m *UpdateAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthorResponse) ProtoMessage()    {}
func (*UpdateAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{7}
}

func (m *UpdateAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthorResponse.Unmarshal(m, b)
}
func (m *UpdateAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthorResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthorResponse.Merge(m, src)
}
func (m *UpdateAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthorResponse.Size(m)
}
func (m *UpdateAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthorResponse proto.InternalMessageInfo

func (m *UpdateAuthorResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteAuthorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthorRequest) Reset()         { *m = DeleteAuthorRequest{} }
func (m *DeleteAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthorRequest) ProtoMessage()    {}
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{8}
}

func (m *DeleteAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthorRequest.Unmarshal(m, b)
}
func (m *DeleteAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthorRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthorRequest.Merge(m, src)
}
func (m *DeleteAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthorRequest.Size(m)
}
func (m *DeleteAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthorRequest proto.InternalMessageInfo

func (m *DeleteAuthorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAuthorResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthorResponse) Reset()         { *m = DeleteAuthorResponse{} }
func (m *DeleteAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthorResponse) ProtoMessage()    {}
func (*DeleteAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6b431d2d514da4a, []int{9}
}

func (m *DeleteAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthorResponse.Unmarshal(m, b)
}
func (m *DeleteAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthorResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthorResponse.Merge(m, src)
}
func (m *DeleteAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthorResponse.Size(m)
}
func (m *DeleteAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthorResponse proto.InternalMessageInfo

func (m *DeleteAuthorResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Author)(nil), "genproto.Author")
	proto.RegisterType((*CreateAuthorRequest)(nil), "genproto.CreateAuthorRequest")
	proto.RegisterType((*CreateAuthorResponse)(nil), "genproto.CreateAuthorResponse")
	proto.RegisterType((*GetAuthorRequest)(nil), "genproto.GetAuthorRequest")
	proto.RegisterType((*GetAuthorResponse)(nil), "genproto.GetAuthorResponse")
	proto.RegisterType((*GetAuthorByIdRequest)(nil), "genproto.GetAuthorByIdRequest")
	proto.RegisterType((*UpdateAuthorRequest)(nil), "genproto.UpdateAuthorRequest")
	proto.RegisterType((*UpdateAuthorResponse)(nil), "genproto.UpdateAuthorResponse")
	proto.RegisterType((*DeleteAuthorRequest)(nil), "genproto.DeleteAuthorRequest")
	proto.RegisterType((*DeleteAuthorResponse)(nil), "genproto.DeleteAuthorResponse")
}

func init() { proto.RegisterFile("protos/author_service/author.proto", fileDescriptor_f6b431d2d514da4a) }

var fileDescriptor_f6b431d2d514da4a = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x5d, 0xb7, 0xaf, 0xfb, 0xd6, 0xfb, 0x7d, 0x93, 0x99, 0x0d, 0x29, 0x1d, 0x1b, 0x23, 0xa0,
	0x0c, 0x1f, 0x2a, 0xcc, 0x1f, 0x20, 0xdb, 0x44, 0xf1, 0x45, 0xa1, 0x22, 0x88, 0x2f, 0xa3, 0xae,
	0x99, 0x2b, 0x74, 0xeb, 0x6c, 0x52, 0xc1, 0x5f, 0x21, 0xf8, 0x8b, 0xa5, 0x49, 0xba, 0x25, 0xb5,
	0x0e, 0x7c, 0xeb, 0xbd, 0xe7, 0xe6, 0xe4, 0x9e, 0x73, 0x42, 0x01, 0x6f, 0x92, 0x98, 0xc5, 0xf4,
	0xcc, 0x4f, 0xd9, 0x32, 0x4e, 0x66, 0x94, 0x24, 0x6f, 0xe1, 0x9c, 0xc8, 0xd2, 0xe5, 0x20, 0x6a,
	0xbc, 0x90, 0x35, 0xff, 0xc2, 0x9f, 0x06, 0xd4, 0xc7, 0x1c, 0x42, 0x07, 0x50, 0x0d, 0x03, 0xdb,
	0x18, 0x18, 0x43, 0xcb, 0xab, 0x86, 0x01, 0xea, 0x82, 0xb5, 0x48, 0xa3, 0x68, 0xb6, 0xf6, 0x57,
	0xc4, 0xae, 0xf2, 0x76, 0x23, 0x6b, 0xdc, 0xfa, 0x2b, 0x82, 0x7a, 0x00, 0xf3, 0x84, 0xf8, 0x8c,
	0x04, 0x33, 0x9f, 0xd9, 0x35, 0x8e, 0x5a, 0xb2, 0x33, 0x66, 0x19, 0x9c, 0x6e, 0x82, 0x1c, 0xfe,
	0x23, 0x60, 0xd9, 0x11, 0x70, 0x40, 0x22, 0x22, 0x61, 0x53, 0xc0, 0xb2, 0x33, 0x66, 0x78, 0x04,
	0xed, 0x29, 0xa7, 0x12, 0x9b, 0x79, 0xe4, 0x35, 0x25, 0x94, 0xe9, 0x0b, 0x19, 0xfa, 0x42, 0xf8,
	0x04, 0x3a, 0xfa, 0x19, 0xba, 0x89, 0xd7, 0x94, 0x14, 0x55, 0xe1, 0x47, 0x68, 0x5d, 0x13, 0xa6,
	0x13, 0x77, 0xc0, 0x8c, 0xc2, 0x55, 0xc8, 0xf8, 0x98, 0xe9, 0x89, 0x02, 0x1d, 0x41, 0x3d, 0x5e,
	0x2c, 0x28, 0x61, 0x5c, 0xbc, 0xe9, 0xc9, 0x2a, 0xeb, 0x53, 0xe2, 0x27, 0xf3, 0xa5, 0x94, 0x2d,
	0x2b, 0x7c, 0x01, 0x87, 0x0a, 0xb3, 0xbc, 0xfe, 0x14, 0xfe, 0x0a, 0xe7, 0xa9, 0x6d, 0x0c, 0x6a,
	0xc3, 0x7f, 0xa3, 0x96, 0x9b, 0x7b, 0xef, 0xca, 0xd1, 0x7c, 0x20, 0x93, 0xb0, 0x25, 0x98, 0xbc,
	0xdf, 0x04, 0xf9, 0x7a, 0x45, 0x09, 0x13, 0x68, 0x3f, 0x70, 0x2b, 0x75, 0x15, 0xbf, 0xc9, 0x0f,
	0xbb, 0xd0, 0xd1, 0x39, 0xe4, 0xbe, 0x99, 0x38, 0xe6, 0xb3, 0x94, 0x4a, 0x22, 0x59, 0xe1, 0x63,
	0x68, 0x5f, 0xf2, 0x7c, 0xf6, 0xde, 0x99, 0xd1, 0xea, 0x63, 0xfb, 0x69, 0x47, 0x1f, 0x35, 0x68,
	0x8a, 0xd1, 0x7b, 0xf1, 0x4e, 0xd1, 0x1d, 0xfc, 0x57, 0x73, 0x44, 0xbd, 0x9d, 0x5f, 0x25, 0x6f,
	0xc2, 0xe9, 0xff, 0x04, 0x8b, 0x8b, 0x71, 0x05, 0x5d, 0x81, 0xb5, 0x75, 0x15, 0x39, 0xbb, 0xf1,
	0xe2, 0x2b, 0x70, 0xba, 0xa5, 0xd8, 0x96, 0x67, 0x0a, 0x4d, 0x2d, 0x1d, 0xd4, 0x2f, 0x99, 0x57,
	0x62, 0x73, 0xbe, 0x25, 0x8d, 0x2b, 0x99, 0x3a, 0xd5, 0x76, 0x55, 0x5d, 0x49, 0xa4, 0xaa, 0xba,
	0xb2, 0xb4, 0x04, 0xa1, 0x6a, 0xb8, 0x4a, 0x58, 0x92, 0x97, 0x4a, 0x58, 0x96, 0x13, 0xae, 0x4c,
	0xd0, 0x53, 0xcb, 0x2d, 0xfc, 0x3b, 0x9e, 0xeb, 0xfc, 0xc4, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0x1c, 0x75, 0xa0, 0x5b, 0x04, 0x00, 0x00,
}
