// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/article_service/article.proto

package article_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Content) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Article struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Article) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Article) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Article) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Article) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateArticleRequest struct {
	Content              *Content `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleRequest) Reset()         { *m = CreateArticleRequest{} }
func (m *CreateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest) ProtoMessage()    {}
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{2}
}

func (m *CreateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest.Unmarshal(m, b)
}
func (m *CreateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest.Merge(m, src)
}
func (m *CreateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest.Size(m)
}
func (m *CreateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest proto.InternalMessageInfo

func (m *CreateArticleRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateArticleRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type CreateArticleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleResponse) Reset()         { *m = CreateArticleResponse{} }
func (m *CreateArticleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateArticleResponse) ProtoMessage()    {}
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{3}
}

func (m *CreateArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleResponse.Unmarshal(m, b)
}
func (m *CreateArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleResponse.Marshal(b, m, deterministic)
}
func (m *CreateArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleResponse.Merge(m, src)
}
func (m *CreateArticleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateArticleResponse.Size(m)
}
func (m *CreateArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleResponse proto.InternalMessageInfo

func (m *CreateArticleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetArticleListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{4}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetArticleListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetArticleListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetArticleListResponse struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetArticleListResponse) Reset()         { *m = GetArticleListResponse{} }
func (m *GetArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleListResponse) ProtoMessage()    {}
func (*GetArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{5}
}

func (m *GetArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListResponse.Unmarshal(m, b)
}
func (m *GetArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListResponse.Merge(m, src)
}
func (m *GetArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleListResponse.Size(m)
}
func (m *GetArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListResponse proto.InternalMessageInfo

func (m *GetArticleListResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type GetArticleByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIdRequest) Reset()         { *m = GetArticleByIdRequest{} }
func (m *GetArticleByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIdRequest) ProtoMessage()    {}
func (*GetArticleByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{6}
}

func (m *GetArticleByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIdRequest.Unmarshal(m, b)
}
func (m *GetArticleByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIdRequest.Merge(m, src)
}
func (m *GetArticleByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIdRequest.Size(m)
}
func (m *GetArticleByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIdRequest proto.InternalMessageInfo

func (m *GetArticleByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetArticleByIdResponse struct {
	Id                   string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content                       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author               *GetArticleByIdResponse_Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string                         `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                         `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string                         `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetArticleByIdResponse) Reset()         { *m = GetArticleByIdResponse{} }
func (m *GetArticleByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIdResponse) ProtoMessage()    {}
func (*GetArticleByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{7}
}

func (m *GetArticleByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIdResponse.Unmarshal(m, b)
}
func (m *GetArticleByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIdResponse.Merge(m, src)
}
func (m *GetArticleByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIdResponse.Size(m)
}
func (m *GetArticleByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIdResponse proto.InternalMessageInfo

func (m *GetArticleByIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetArticleByIdResponse) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GetArticleByIdResponse) GetAuthor() *GetArticleByIdResponse_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *GetArticleByIdResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetArticleByIdResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetArticleByIdResponse) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type GetArticleByIdResponse_Author struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIdResponse_Author) Reset()         { *m = GetArticleByIdResponse_Author{} }
func (m *GetArticleByIdResponse_Author) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIdResponse_Author) ProtoMessage()    {}
func (*GetArticleByIdResponse_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{7, 0}
}

func (m *GetArticleByIdResponse_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIdResponse_Author.Unmarshal(m, b)
}
func (m *GetArticleByIdResponse_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIdResponse_Author.Marshal(b, m, deterministic)
}
func (m *GetArticleByIdResponse_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIdResponse_Author.Merge(m, src)
}
func (m *GetArticleByIdResponse_Author) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIdResponse_Author.Size(m)
}
func (m *GetArticleByIdResponse_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIdResponse_Author.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIdResponse_Author proto.InternalMessageInfo

func (m *GetArticleByIdResponse_Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetArticleByIdResponse_Author) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *GetArticleByIdResponse_Author) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetArticleByIdResponse_Author) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetArticleByIdResponse_Author) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type UpdateArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleRequest) Reset()         { *m = UpdateArticleRequest{} }
func (m *UpdateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleRequest) ProtoMessage()    {}
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{8}
}

func (m *UpdateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleRequest.Unmarshal(m, b)
}
func (m *UpdateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleRequest.Merge(m, src)
}
func (m *UpdateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleRequest.Size(m)
}
func (m *UpdateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleRequest proto.InternalMessageInfo

func (m *UpdateArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateArticleRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type UpdateArticleResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleResponse) Reset()         { *m = UpdateArticleResponse{} }
func (m *UpdateArticleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleResponse) ProtoMessage()    {}
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{9}
}

func (m *UpdateArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleResponse.Unmarshal(m, b)
}
func (m *UpdateArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleResponse.Merge(m, src)
}
func (m *UpdateArticleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleResponse.Size(m)
}
func (m *UpdateArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleResponse proto.InternalMessageInfo

func (m *UpdateArticleResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArticleRequest) Reset()         { *m = DeleteArticleRequest{} }
func (m *DeleteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArticleRequest) ProtoMessage()    {}
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{10}
}

func (m *DeleteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArticleRequest.Unmarshal(m, b)
}
func (m *DeleteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArticleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArticleRequest.Merge(m, src)
}
func (m *DeleteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArticleRequest.Size(m)
}
func (m *DeleteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArticleRequest proto.InternalMessageInfo

func (m *DeleteArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteArticleResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArticleResponse) Reset()         { *m = DeleteArticleResponse{} }
func (m *DeleteArticleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteArticleResponse) ProtoMessage()    {}
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b002992b6273b9, []int{11}
}

func (m *DeleteArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArticleResponse.Unmarshal(m, b)
}
func (m *DeleteArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArticleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArticleResponse.Merge(m, src)
}
func (m *DeleteArticleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteArticleResponse.Size(m)
}
func (m *DeleteArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArticleResponse proto.InternalMessageInfo

func (m *DeleteArticleResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Content)(nil), "genproto.Content")
	proto.RegisterType((*Article)(nil), "genproto.Article")
	proto.RegisterType((*CreateArticleRequest)(nil), "genproto.CreateArticleRequest")
	proto.RegisterType((*CreateArticleResponse)(nil), "genproto.CreateArticleResponse")
	proto.RegisterType((*GetArticleListRequest)(nil), "genproto.GetArticleListRequest")
	proto.RegisterType((*GetArticleListResponse)(nil), "genproto.GetArticleListResponse")
	proto.RegisterType((*GetArticleByIdRequest)(nil), "genproto.GetArticleByIdRequest")
	proto.RegisterType((*GetArticleByIdResponse)(nil), "genproto.GetArticleByIdResponse")
	proto.RegisterType((*GetArticleByIdResponse_Author)(nil), "genproto.GetArticleByIdResponse.Author")
	proto.RegisterType((*UpdateArticleRequest)(nil), "genproto.UpdateArticleRequest")
	proto.RegisterType((*UpdateArticleResponse)(nil), "genproto.UpdateArticleResponse")
	proto.RegisterType((*DeleteArticleRequest)(nil), "genproto.DeleteArticleRequest")
	proto.RegisterType((*DeleteArticleResponse)(nil), "genproto.DeleteArticleResponse")
}

func init() {
	proto.RegisterFile("protos/article_service/article.proto", fileDescriptor_e9b002992b6273b9)
}

var fileDescriptor_e9b002992b6273b9 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0xb5, 0x2c, 0x4b, 0xb6, 0x27, 0x7c, 0x86, 0xec, 0x27, 0x07, 0xe1, 0xd0, 0xc6, 0x2c, 0xa5,
	0x29, 0x94, 0x2a, 0xe0, 0x3c, 0x40, 0x71, 0x52, 0x08, 0x81, 0xd2, 0x0b, 0x85, 0xdc, 0x14, 0x8a,
	0xab, 0x48, 0xeb, 0x46, 0x20, 0x4b, 0xae, 0x76, 0x55, 0xc8, 0x1b, 0xf4, 0xba, 0x8f, 0xd3, 0xab,
	0x3e, 0x5a, 0xd1, 0xee, 0xa8, 0x59, 0x29, 0x1b, 0x43, 0x09, 0xbd, 0xd3, 0xfc, 0xec, 0x99, 0x33,
	0x33, 0x67, 0x6c, 0x78, 0xb1, 0x2d, 0x0b, 0x51, 0xf0, 0x93, 0xa8, 0x14, 0x69, 0x9c, 0xb1, 0x15,
	0x67, 0xe5, 0xb7, 0x34, 0x66, 0x8d, 0x1d, 0xc8, 0x30, 0x19, 0x7d, 0x61, 0xb9, 0xfc, 0xa2, 0xa7,
	0x30, 0x3c, 0x2f, 0x72, 0xc1, 0x72, 0x41, 0x3c, 0x70, 0x44, 0x2a, 0x32, 0xe6, 0x5b, 0x73, 0xeb,
	0xd5, 0x38, 0x54, 0x06, 0x21, 0x30, 0xb8, 0x29, 0x92, 0x3b, 0xbf, 0x2f, 0x9d, 0xf2, 0x9b, 0xfe,
	0xb2, 0x60, 0xb8, 0x54, 0x80, 0x64, 0x02, 0xfd, 0x34, 0xc1, 0x27, 0xfd, 0x34, 0x21, 0xaf, 0x61,
	0x18, 0x2b, 0x40, 0xf9, 0x64, 0x6f, 0xb1, 0x1f, 0x34, 0xc5, 0x02, 0xac, 0x14, 0x36, 0x19, 0xe4,
	0x10, 0xc6, 0x51, 0x25, 0x6e, 0x8b, 0x72, 0x95, 0x26, 0xbe, 0x2d, 0x31, 0x46, 0xca, 0x71, 0x99,
	0x90, 0x67, 0x00, 0x71, 0xc9, 0x22, 0xc1, 0x92, 0x55, 0x24, 0xfc, 0x81, 0x8c, 0x8e, 0xd1, 0xb3,
	0x14, 0x75, 0xb8, 0xda, 0x26, 0x4d, 0xd8, 0x51, 0x61, 0xf4, 0xa8, 0x70, 0xc2, 0x32, 0x86, 0x61,
	0x57, 0x85, 0xd1, 0xb3, 0x14, 0xf4, 0x33, 0x78, 0xe7, 0x12, 0x0a, 0xfb, 0x08, 0xd9, 0xd7, 0x8a,
	0x71, 0xa1, 0xd3, 0xb7, 0x9e, 0x44, 0x9f, 0x1e, 0xc3, 0xb4, 0x53, 0x81, 0x6f, 0x8b, 0x9c, 0x3f,
	0x98, 0x18, 0xfd, 0x04, 0xd3, 0x0b, 0x26, 0x30, 0xeb, 0x7d, 0xca, 0x45, 0xc3, 0xc5, 0x03, 0x27,
	0x4b, 0x37, 0xa9, 0x62, 0xe2, 0x84, 0xca, 0x20, 0x07, 0xe0, 0x16, 0xeb, 0x35, 0x67, 0x6a, 0xbe,
	0x4e, 0x88, 0x56, 0xed, 0xe7, 0x2c, 0x2a, 0xe3, 0x5b, 0x64, 0x82, 0x16, 0xbd, 0x80, 0x83, 0x2e,
	0x3c, 0x12, 0x79, 0x03, 0x23, 0x94, 0x05, 0xf7, 0xad, 0xb9, 0xdd, 0x6e, 0xb6, 0x61, 0xfd, 0x27,
	0xa5, 0x6e, 0xe8, 0x1e, 0xe8, 0xec, 0xee, 0x32, 0x69, 0x78, 0x76, 0x1b, 0xfa, 0x6e, 0xeb, 0x25,
	0x55, 0xa6, 0xb9, 0xf7, 0xbf, 0x53, 0xcb, 0x5b, 0x70, 0xd5, 0x74, 0x65, 0x87, 0x7b, 0x8b, 0xe3,
	0xfb, 0x5c, 0x73, 0xb9, 0x60, 0x29, 0xd3, 0x43, 0x7c, 0xf6, 0x4f, 0x15, 0x35, 0xfb, 0x61, 0x81,
	0xab, 0xea, 0x3d, 0xe8, 0xf2, 0x10, 0xc6, 0xeb, 0x2a, 0xcb, 0x56, 0x79, 0xb4, 0x61, 0x78, 0x48,
	0xa3, 0xda, 0xf1, 0x21, 0xda, 0xb0, 0x0e, 0x29, 0x7b, 0x37, 0xa9, 0xc1, 0x6e, 0x52, 0x4e, 0x57,
	0xe6, 0x57, 0xe0, 0x5d, 0xcb, 0xdc, 0x8e, 0xcc, 0x9f, 0xb2, 0x07, 0x7a, 0x02, 0xd3, 0x0e, 0x28,
	0x6e, 0xb7, 0x96, 0xa0, 0x88, 0x44, 0xc5, 0x11, 0x19, 0x2d, 0xfa, 0x12, 0xbc, 0x77, 0x92, 0xd2,
	0x6e, 0x16, 0x35, 0x70, 0x27, 0x6f, 0x37, 0xf0, 0xe2, 0xa7, 0x0d, 0x13, 0xcc, 0xbd, 0x52, 0x3f,
	0x74, 0x24, 0x84, 0xff, 0x5a, 0x67, 0x47, 0x9e, 0x6b, 0x9d, 0x18, 0x2e, 0x7e, 0x76, 0xf4, 0x68,
	0x5c, 0x15, 0xa7, 0x3d, 0x72, 0x0d, 0x93, 0xf6, 0x09, 0x91, 0x23, 0x93, 0xf4, 0xb4, 0xdb, 0x9d,
	0xcd, 0x1f, 0x4f, 0x30, 0xc3, 0xd6, 0xba, 0x35, 0xc3, 0x6a, 0xa7, 0x66, 0x86, 0xd5, 0x25, 0x4f,
	0x7b, 0xf5, 0x04, 0x5a, 0xeb, 0xd1, 0x27, 0x60, 0x12, 0x83, 0x3e, 0x01, 0xe3, 0x5e, 0x15, 0x66,
	0x6b, 0x33, 0x3a, 0xa6, 0x69, 0xb5, 0x3a, 0xa6, 0x71, 0xa5, 0xb4, 0x77, 0xf6, 0xff, 0xc7, 0xfd,
	0xa0, 0xfb, 0x3f, 0x75, 0xe3, 0xca, 0x37, 0xa7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x92,
	0x27, 0x6c, 0xc8, 0x06, 0x00, 0x00,
}
